# Custom Favicon
favicon: favicon.png
# Site name
name: Seasky
# Support for http2 push features
http2: true
# Hide last modified at date
hide_last_modified: false
# Support for http2 push features
http2_resources:
  - rel: preload
    as: image
    href: /assets/images/logo.png
# Ascii Art
ascii-art: ascii-art.html
# Site Slogan
slogan: Leading
# Mailchimp settings
mailchimp:
    enabled: false
    id: 
    unsubscribe-url: 
# Footer Newsletter toggle.
newsletter:
    enabled: false
    url: 
tags_enabled: true
jumbotron:
  darken: true
# Footer Image default is linaro sprinkle
linaro-footer-image: logo.png
# # Breadcrumb Settings
# breadcrumb:
#     image: breadcrumb-image.jpg
#Content Repo for static site.
# Used for the edit on github include
edit-on-github:
    enabled: false
    repo:
# Settings for the home page
home:
    #Content Background Image E.g. DeviceTree.org
    # content-image: background-image.png
    # If this is set then the navigation will be transparent.
    transparent-nav: true
    # If this is set to true then the shape divider will be displayed
    shaped-divider: false
    # Jumbotron settings for the home page
    jumbotron:
        # Include file to replace all the contents of the jumbotron with.
        included_file: hero-banner.html
        # Toggle the jumbotron
        enabled: true
        # Background image for the home page located in assets/images
        background-image:
            # Darken is set to true by default - if you wish to remove the image overlay
            # then change this setting to false.
            darken: true
            # This is the name of the background-image located in /assets/images/
            name: logo.png
        # image: devicetree-icon-white.png
# Jekyll social media site settings. Github, LinkedIn, Google+, Facebook and Youtube
github_username:
linkedin_username:
facebook_username:
youtube_username:
twitter_username:
slideshare_username:
tdb: 376022733
# Blog setup
blog:
    # Url for the blog tags page
    tags_page: /blog/tag/
    # Show Thumbnails in the post index
    show_thumbnails: true
    # Toggle the output of blog/news reading time.
    reading_time: true
    # Toggle site wide comments display.
    comments: true
    # Post Side Bar Settings
    sidebar:
        display-on-posts: true
        display-on-index: true
        # Toggle whether or not thumbnails in the sidebar are displayed.
        thumbnails:
            display: true
        # Display other posts contained in _posts
        other-posts:
            display: true
            count: 4
        # Display Related posts based on tags / categories
        related-posts:
            display: true
            count: 5
        # Display the most recent posts
        most-recent-posts:
            display: true
            count: 5

# Google Anayltics Setup
google:
    tag_manager:
# Shema.org settings used in the schema.html include.
schema:
    enabled: false
    organisation:
        name: Seasky
        url: https://seasky.jp
        sameAs:
        address:

# Disqus Comments
disqus:
    enabled: true
    shortname: Seasky
# Placeholder for Missing Images
placeholder: /assets/images
